### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-myv#1]
When building the mobile speller for divvun.org, the compilation fails

./configure --without-forrest --enable-spellers --disable-hfst-desktop-spellers --prefix=$HOME/.local --enable-hfst-mobile-speller

/usr/bin/hfst-lexc: The file lexicon.tmp.lexc did not compile cleanly.

**Comment by Trondtr** [comment]
For documentation:
 Warning: Sublexicons defined but not used
PROP-PATR-MAL_END-IN-CH/DZ 
*** ERROR: could not parse lexc file: treating warnings as errors [--Werror] ***

Commenting out the unused lexicon, checked in revision , now it compiles..

**Comment by snomos** [comment]
Chiara fekk same feil i mdf på måndag (jf https://giella.zulipchat.com/#narrow/stream/238727-mdf/topic/Kompilering.20feil) - det viste seg at ho ikkje hadde oppdatert giella-shared. Kan det vera tilfelle her òg? @Trondtr @albbas ?

**Comment by albbas** [comment]
Stemmer det.
